language: generic

services:
- docker

before_script:
- sudo service mysql stop
- docker-compose -f docker-compose.travis.yml up --build
- docker-compose down
- docker-compose -f docker-compose.travis.yml up -d
- docker ps -a
script:
# Run unit tests in the app container
#- docker-compose exec -T app vendor/bin/php-cs-fixer fix app --verbose
- docker-compose exec -T app vendor/bin/phpunit