language: generic

sudo: required

services:
- docker

before_script:
- docker-compose up --build -d

script:
- components/app/vendor/bin/phpunit --bootstrap components/app/vendor/autoload.php tests

after_script:
- docker-compose down