version: "3"

volumes:
  dbdata: {}

services:
  app:
    build:
      context: ./components/app
      dockerfile: develop/Dockerfile
      args:
        - XDEBUG_PORT=${XDEBUG_PORT:-172.18.0.1}
#   env_file: ./config/local/app.env
    volumes:
      - ./components/app/src:/var/www
    depends_on:
      - db

  server:
    build: 
      context: ./components/server
      dockerfile: develop/Dockerfile
    env_file: ./config/local/server.env    
    volumes:
      - ./components/app/src:/var/www
    ports:
      - 80:80
    depends_on: 
      - app

  db:
    image: mysql:5.7.19
    env_file: ./config/local/db.env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  test:
    build:
      context: ./components/app
      dockerfile: develop/tests.Dockerfile
      args:
        - XDEBUG_PORT=${XDEBUG_PORT:-172.18.0.1}
    volumes:
      - ./components/app/src:/var/www

#  queue-worker:
#    env_file: ./config/local/app.env
#    volumes:
#      - ./components/app/src:/var/www:cached
#    depends_on:
#      - app
#    command: php artisan queue:work
#    restart: unless-stopped
#
#  build:
#    image: node:8.7.0-alpine
#    volumes:
#      - ./components/app/src:/build:cached
#    depends_on:
#      - app
#    working_dir: /build
#    command: sh -c "npm install && npm rebuild node-sass && npm run dev"

