version: "3"

volumes:
  dbdata: {}

services:
  app:
    build:
      context: ./components/app
      dockerfile: develop/Dockerfile
      args:
      - XDEBUG_PORT=${XDEBUG_PORT:-172.18.0.1}
    volumes:
    - ./components/app/src:/var/www:cached